### ISSUE TITLE
Tracking changes requested in merged PR #307

### ISSUE THREAD

**Issue by alexandraBara** [ROCm/MIOpen#560]
@atamazov  I will address changes requested here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307 in an upcoming PR as we want to unblock this PR: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533

also to address:

Find IsCacheDisabled() in binary_cache.cpp
Rename it to IsBinaryCacheDisabled()
Make it global (remove static and add its declaration to binary_cache.hpp)
Use it here instead of MIOPEN_ENABLE_SQLITE_KERN_CACHE

TODO: src/ocl/convolutionocl.cpp perf_db.emoty() check needs to be:

perf_db.emty() and device_cu/compile_only etc not set --> throw error
Otherwise we are still seeing "..incorrect params" thrown from here bc Invokers dont populate the perf_db during compile_only

**Comment by atamazov** [comment]
@alexandraBara Direct links to relevant items:
- [ ] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#discussion_r513783447
- [ ] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#discussion_r515365226
- [ ] leftovers of https://github.com/ROCmSoftwarePlatform/MIOpen/pull/307#pullrequestreview-518920649

**Comment by atamazov** [comment]
@alexandraBara Any progress?

**Comment by atamazov** [comment]
- [ ] :bug: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#pullrequestreview-527654975

**Comment by alexandraBara** [comment]
> @alexandraBara Any progress?

@atamazov  I have been tuning and I am about to finish with it. I picked up this task today and started working on it. Should have a PR this week.

**Comment by atamazov** [comment]
@alexandraBara Good, thank you!

**Comment by daniellowell** [comment]
@alexandraBara @atamazov Is this `urgency_blocker` ticket ready to close?

**Comment by atamazov** [comment]
@daniellowell I don't think so.

**Comment by atamazov** [comment]
The TODO list at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/560#issuecomment-719842997 is updated. Note that there is one bug that presumably affects auto-tuning, not fixed for long.

**Comment by DrizztDoUrden** [comment]
About auto-tuning: lines like `MIOPEN_FIND_ENFORCE=SEARCH_DB_UPDATE bin/MIOpenDriver conv -x 1 -y 1` fail horribly.

**Comment by DrizztDoUrden** [comment]
@daniellowell I guess that's worth investigation and if I understood correctly, @atamazov has found the PR which caused it: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/533#discussion_r520911050

**Comment by atamazov** [comment]
The library that has the issue marked with :red_circle: at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/560#issuecomment-719842997 must not be released.

**Comment by atamazov** [comment]
@junliume The [TODO list](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/560#issuecomment-719842997) is not done. Shall we really close this ticket?

**Comment by ppanchad-amd** [comment]
@alexandraBara Is this still an issue with the latest ROCm 6.1.1? Thanks!

**Comment by JonathanLichtnerAMD** [comment]
Closing since MIOpen is being migrated to [ROCm/rocm-libraries](https://github.com/ROCm/rocm-libraries).  Please re-open there if you believe this is still an issue.
